// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
  {"name":"Stillnight_ThreeJS","status":true,"description":"Renders Map and Battle in 3D using Three.js","parameters":{}}
];
